# Generated by Django 4.2.7 on 2025-09-06 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_count', models.IntegerField(default=0)),
                ('average_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage change from previous period', max_digits=5)),
            ],
            options={
                'verbose_name': 'Expense Analytics',
                'verbose_name_plural': 'Expense Analytics',
                'db_table': 'expense_analytics',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'db_table': 'generated_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('expense_summary', 'Expense Summary'), ('group_analysis', 'Group Analysis'), ('category_breakdown', 'Category Breakdown'), ('trend_analysis', 'Trend Analysis'), ('settlement_report', 'Settlement Report'), ('custom', 'Custom Report')], max_length=30)),
                ('filters', models.JSONField(default=dict)),
                ('fields', models.JSONField(default=list)),
                ('grouping', models.JSONField(default=dict)),
                ('sorting', models.JSONField(default=dict)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('styling', models.JSONField(default=dict)),
                ('is_public', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'db_table': 'report_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSpendingPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_date', models.DateField(db_index=True)),
                ('most_active_day', models.CharField(blank=True, max_length=10)),
                ('most_active_hour', models.IntegerField(blank=True, null=True)),
                ('top_categories', models.JSONField(default=list)),
                ('category_distribution', models.JSONField(default=dict)),
                ('average_expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('expense_frequency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('group_vs_individual_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('most_active_groups', models.JSONField(default=list)),
                ('seasonal_spending', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'User Spending Pattern',
                'verbose_name_plural': 'User Spending Patterns',
                'db_table': 'user_spending_patterns',
                'ordering': ['-analysis_date'],
            },
        ),
    ]
