# Generated by Django 4.2.7 on 2025-09-06 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userspendingpattern',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spending_patterns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_report_templates', to='groups.group'),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_report_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='analytics.reporttemplate'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_analytics', to='core.category'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics', to='core.currency'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_analytics', to='groups.group'),
        ),
        migrations.AddField(
            model_name='expenseanalytics',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userspendingpattern',
            unique_together={('user', 'analysis_date')},
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['created_by', 'report_type'], name='report_temp_created_4bf7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_public', 'usage_count'], name='report_temp_is_publ_23414f_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by', 'status'], name='generated_r_generat_87ea60_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status', 'expires_at'], name='generated_r_status_c55784_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseanalytics',
            index=models.Index(fields=['user', 'period_type', 'period_start'], name='expense_ana_user_id_84e7f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseanalytics',
            index=models.Index(fields=['group', 'period_type', 'period_start'], name='expense_ana_group_i_1063e9_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseanalytics',
            index=models.Index(fields=['category', 'period_start'], name='expense_ana_categor_9b674c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expenseanalytics',
            unique_together={('user', 'group', 'category', 'period_type', 'period_start')},
        ),
    ]
