# Generated by Django 4.2.7 on 2026-02-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("expense_added", "Expense Added"),
                    ("expense_updated", "Expense Updated"),
                    ("expense_comment", "Expense Comment"),
                    ("group_invitation", "Group Invitation"),
                    ("group_joined", "Group Joined"),
                    ("group_left", "Group Left"),
                    ("payment_due", "Payment Due"),
                    ("payment_received", "Payment Received"),
                    ("settlement_request", "Settlement Request"),
                    ("settlement_completed", "Settlement Completed"),
                    ("reminder", "Reminder"),
                    ("system", "System Notification"),
                    ("budget_velocity_alert", "Budget Velocity Alert"),
                    ("budget_threshold_alert", "Budget Threshold Alert"),
                    ("budget_unassigned_reminder", "Unassigned Budget Reminder"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("expense_added", "Expense Added"),
                    ("expense_updated", "Expense Updated"),
                    ("expense_comment", "Expense Comment"),
                    ("group_invitation", "Group Invitation"),
                    ("group_joined", "Group Joined"),
                    ("group_left", "Group Left"),
                    ("payment_due", "Payment Due"),
                    ("payment_received", "Payment Received"),
                    ("settlement_request", "Settlement Request"),
                    ("settlement_completed", "Settlement Completed"),
                    ("reminder", "Reminder"),
                    ("system", "System Notification"),
                    ("budget_velocity_alert", "Budget Velocity Alert"),
                    ("budget_threshold_alert", "Budget Threshold Alert"),
                    ("budget_unassigned_reminder", "Unassigned Budget Reminder"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notificationtemplate",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("expense_added", "Expense Added"),
                    ("expense_updated", "Expense Updated"),
                    ("expense_comment", "Expense Comment"),
                    ("group_invitation", "Group Invitation"),
                    ("group_joined", "Group Joined"),
                    ("group_left", "Group Left"),
                    ("payment_due", "Payment Due"),
                    ("payment_received", "Payment Received"),
                    ("settlement_request", "Settlement Request"),
                    ("settlement_completed", "Settlement Completed"),
                    ("reminder", "Reminder"),
                    ("system", "System Notification"),
                    ("budget_velocity_alert", "Budget Velocity Alert"),
                    ("budget_threshold_alert", "Budget Threshold Alert"),
                    ("budget_unassigned_reminder", "Unassigned Budget Reminder"),
                ],
                max_length=30,
            ),
        ),
    ]
