# Generated by Django 4.2.7 on 2025-09-06 06:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('recurring', 'Recurring')], default='individual', max_length=20)),
                ('expense_date', models.DateField(db_index=True)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amounts'), ('percentage', 'Percentage'), ('shares', 'Shares'), ('adjustment', 'Adjustment')], default='equal', max_length=20)),
                ('split_data', models.JSONField(default=dict)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('attachments', models.JSONField(default=list)),
                ('ocr_data', models.JSONField(default=dict)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_settled', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False)),
                ('requires_approval', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.category')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.currency')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('parent_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='expenses.expense')),
                ('tags', models.ManyToManyField(blank=True, related_name='expenses', to='core.tag')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'expenses',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(db_index=True)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split'), ('exact', 'Exact Amounts'), ('percentage', 'Percentage'), ('shares', 'Shares'), ('adjustment', 'Adjustment')], default='equal', max_length=20)),
                ('split_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paused', models.BooleanField(default=False)),
                ('paused_until', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expenses', to='core.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_recurring_expenses', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_expenses', to='core.currency')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses_to_pay', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'db_table': 'recurring_expenses',
                'ordering': ['next_due_date', 'title'],
                'indexes': [models.Index(fields=['next_due_date', 'is_active'], name='recurring_e_next_du_b7c97d_idx'), models.Index(fields=['group', 'is_active'], name='recurring_e_group_i_80c6db_idx'), models.Index(fields=['created_by', 'is_active'], name='recurring_e_created_e29ef2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpenseShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('is_settled', models.BooleanField(default=False)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_shares', to='core.currency')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='expenses.expense')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_expense_shares', to=settings.AUTH_USER_MODEL)),
                ('settlement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_shares', to='payments.settlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Share',
                'verbose_name_plural': 'Expense Shares',
                'db_table': 'expense_shares',
                'ordering': ['expense__expense_date', 'user__first_name'],
                'indexes': [models.Index(fields=['user', 'is_settled'], name='expense_sha_user_id_9bc84a_idx'), models.Index(fields=['paid_by', 'is_settled'], name='expense_sha_paid_by_3738b0_idx'), models.Index(fields=['expense', 'user'], name='expense_sha_expense_25e29c_idx')],
                'unique_together': {('expense', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='expenses.expense')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='expenses.expensecomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense Comment',
                'verbose_name_plural': 'Expense Comments',
                'db_table': 'expense_comments',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['expense', 'created_at'], name='expense_com_expense_88a31b_idx'), models.Index(fields=['user', 'created_at'], name='expense_com_user_id_b3e210_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date', 'group'], name='expenses_expense_2e2af7_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by', 'expense_date'], name='expenses_paid_by_69ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='expenses_categor_fcbf9c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_settled', 'group'], name='expenses_is_sett_fb8a8a_idx'),
        ),
    ]
