# Generated by Django 4.2.7 on 2026-01-26 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='ocr_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
