# Generated by Django 4.2.7 on 2026-02-03 21:52

import apps.expenses.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0001_initial"),
        ("expenses", "0002_alter_expense_attachments_alter_expense_ocr_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="user_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="budget.usercategory",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="receipts/",
                validators=[
                    apps.expenses.models.validate_receipt_size,
                    apps.expenses.models.validate_receipt_extension,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "pdf"]
                    ),
                ],
            ),
        ),
    ]
