# Generated by Django 4.2.7 on 2025-09-06 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Group name must be at least 2 characters long'), django.core.validators.MaxLengthValidator(100, 'Group name cannot exceed 100 characters')])),
                ('description', models.TextField(blank=True)),
                ('group_type', models.CharField(choices=[('personal', 'Personal'), ('trip', 'Trip'), ('home', 'Home/Apartment'), ('couple', 'Couple'), ('project', 'Project'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/')),
                ('is_private', models.BooleanField(default=False)),
                ('invite_code', models.CharField(blank=True, max_length=12, unique=True)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.currency')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('left', 'Left'), ('removed', 'Removed')], default='pending', max_length=20)),
                ('invitation_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Membership',
                'verbose_name_plural': 'Group Memberships',
                'db_table': 'group_memberships',
                'ordering': ['joined_at'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='group_membe_group_i_740f30_idx'), models.Index(fields=['user', 'is_active'], name='group_membe_user_id_72052f_idx')],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17)),
                ('message', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_group_invitations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='groups.group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Invitation',
                'verbose_name_plural': 'Group Invitations',
                'db_table': 'group_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'is_accepted'], name='group_invit_email_89b89c_idx'), models.Index(fields=['group', 'is_accepted'], name='group_invit_group_i_830f55_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('member_joined', 'Member Joined'), ('member_left', 'Member Left'), ('expense_added', 'Expense Added'), ('expense_updated', 'Expense Updated'), ('expense_deleted', 'Expense Deleted'), ('payment_made', 'Payment Made'), ('group_updated', 'Group Updated'), ('settlement', 'Settlement')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Activity',
                'verbose_name_plural': 'Group Activities',
                'db_table': 'group_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='group_activ_group_i_2579fa_idx'), models.Index(fields=['user', 'activity_type'], name='group_activ_user_id_7934df_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['name', 'is_active'], name='groups_name_503367_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['invite_code'], name='groups_invite__7fda49_idx'),
        ),
    ]
