# Generated by Django 4.2.7 on 2026-02-03 21:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyBudget",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("month", models.PositiveIntegerField(db_index=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="monthly_budgets",
                        to="core.currency",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Monthly Budget",
                "verbose_name_plural": "Monthly Budgets",
                "db_table": "budget_monthly_budgets",
                "ordering": ["-year", "-month"],
                "unique_together": {("user", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "wallet_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("sinking_fund", "Sinking Fund"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("rollover_enabled", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="#4CAF50", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_wallets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "budget_wallets",
                "ordering": ["order", "name"],
                "unique_together": {("user", "name")},
            },
        ),
        migrations.CreateModel(
            name="WalletAdjustment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Positive = boost, negative = deduction",
                        max_digits=15,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_adjustments",
                        to="budget.monthlybudget",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="budget.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Adjustment",
                "verbose_name_plural": "Wallet Adjustments",
                "db_table": "budget_wallet_adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_assignments",
                        to="core.category",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_assignments",
                        to="budget.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Category Assignment",
                "verbose_name_plural": "Wallet Category Assignments",
                "db_table": "budget_wallet_categories",
                "unique_together": {("wallet", "category")},
            },
        ),
        migrations.CreateModel(
            name="WalletAllocation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "rollover_from_previous",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "accumulated_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="For sinking funds: accumulated balance.",
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "monthly_budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_allocations",
                        to="budget.monthlybudget",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="budget.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Allocation",
                "verbose_name_plural": "Wallet Allocations",
                "db_table": "budget_wallet_allocations",
                "unique_together": {("monthly_budget", "wallet")},
            },
        ),
        migrations.CreateModel(
            name="UserCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(default="#9E9E9E", max_length=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_categories",
                        to="budget.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Category",
                "verbose_name_plural": "User Categories",
                "db_table": "budget_user_categories",
                "ordering": ["name"],
                "unique_together": {("wallet", "name")},
            },
        ),
    ]
